//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library1Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Members()
        {
            this.Borrow = new HashSet<Borrow>();
        }
    
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string MembershipDate { get; set; }
        public string Email { get; set; }
        public string PhotoMember { get; set; }
        public Nullable<int> MemberNum { get; set; }
        public string BeginDate { get; set; }
        public string NationalCode { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> EducationId { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrow> Borrow { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Education Education { get; set; }
    }
}
