//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library1Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermissions
    {
        public long Id { get; set; }
        public int UserId { get; set; }
        public int PermissionId { get; set; }
    
        public virtual Permissions Permissions { get; set; }
        public virtual Users Users { get; set; }
    }
}
